version: '3.8'

networks:
  db:

volumes:
  common_psql_ma:

services:
  psql_db:
    build:
      context: "./psql"
    container_name: psql_cont
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - db
    volumes:
      - common_psql_ma:/var/lib/postgresql/data

  dal_flights:
    build:
      context: ./Core/Dal_flights
    container_name: dal_flights
    depends_on:
      - psql_db
    networks:
      - db
    # ports:
    #   - "74:12001"
    environment:
      TYPE_OF_DB: psql
      PSQL_DB_USER: postgres
      PSQL_DB_PASSWORD: 123
      PSQL_DB_HOST: psql_cont
      PSQL_DB_PORT: 5432
      PSQL_DB_DBNAME: airplanesco
      PSQL_TABLE_NAME: Flights
      PSQL_LIMIT_RESPONSE_TIME: 10

  dal_customers:
    build:
      context: ./Core/Dal_customers
    container_name: dal_customers
    depends_on:
      - psql_db
    networks:
      - db
    # ports:
    #   - "75:12000"
    environment:
      PSQL_DB_USER: postgres
      PSQL_DB_PASSWORD: 123
      PSQL_DB_HOST: psql_cont
      PSQL_DB_PORT: 5432
      PSQL_DB_DBNAME: airplanesco
      PSQL_TABLE_NAME: Customers
      PSQL_LIMIT_RESPONSE_TIME: 10    

  # dal_tickets:
  #   build: 
  #     context: ./Core/Dal_tickets
  #   container_name: dal_tickets
  #   depends_on:
  #     - psql_db
  #   networks:
  #     - db
  #   ports:
  #     - "76:12002"
  #   environment:
  #     PSQL_DB_USER: postgres
  #     PSQL_DB_PASSWORD: 123
  #     PSQL_DB_HOST: psql_cont
  #     PSQL_DB_PORT: 5432
  #     PSQL_DB_DBNAME: airplanesco
  #     PSQL_TABLE_NAME: Tickets
  #     PSQL_LIMIT_RESPONSE_TIME: 10

  management_customers:
    build:
      context: ./Core/Management_customers
    container_name: management_customers
    networks:
      - db
    ports:
      - "77:12007"
    environment:
      DAL_CUSTOMERS_URL: http://dal_customers:12000/postgres/customers
      LIMIT_RESPONSE_TIME: 10

  management_flights:
    build:
      context: ./Core/Management_flights
    container_name: management_flights
    networks:
      - db
    ports:
      - "78:12006"
    environment:
      DAL_FLIGHTS_URL: http://dal_flights:12001/postgres/flights
      LIMIT_RESPONSE_TIME: 10

  # management_tickets:
  #   build:
  #     context: ./Core/Management_tickets
  #   container_name: management_tickets
  #   networks:
  #     - db
  #   ports:
  #     - "79:12008"
  #   environment:
  #     DAL_TICKETS_URL: http://dal_tickets:12002/postgres/tickets
  #     LIMIT_RESPONSE_TIME: 10

  # catalog:
  #   build:
  #     context: ./Core/Flights_catalog
  #   container_name: catalog
  #   # ports:
  #   #   - "80:12004"
  #   networks:
  #     - db
  #   environment:
  #     MANAGEMENT_FLIGHTS_URL: http://management_flights:12006/management-flights/flights
  #     LIMIT_RESPONSE_TIME: 5

  # auth:
  #   build: 
  #     context: ./Core/Auth
  #   container_name: auth
  #   # ports:
  #   #   - "81:12005"
  #   networks:
  #     - db
  #   environment:
  #     MANAGEMENT_CUSTOMERS_URL: http://management_customers:12007/management-customers/customers
  #     LIMIT_RESPONSE_TIME: 5

  # cart:
  #   build:
  #     context: ./Core/Cart
  #   container_name: cart
  #   ports:
  #     - "82:12003"
  #   networks:
  #     - db   

  # order_ticket:
  #   build:
  #     context: ./Core/OrderTicket
  #   container_name: order_ticket
  #   ports:
  #     - "83:12009"
  #   networks:
  #     - db
  #   environment:
  #     CART_URL: http://cart:12003/cart
  #     LIMIT_RESPONSE_TIME: 5
  
  # purchased_tickets:
  #   build:
  #     context: ./Core/PurchasedTickets
  #   container_name: purchased_tickets
  #   ports:
  #     - "84:12010"
  #   networks:
  #     - db
  #   environment:
  #     MANAGEMENT_TICKETS_URL: http://management_tickets:12008/management-tickets/tickets
  #     LIMIT_RESPONSE_TIME: 5
  
  cache:
    build:
      context: ./Core/Cache
    container_name: cache
    ports:
      - "85:12011"
    networks:
      - db

  management_cache:
    build: 
      context: ./Core/management_cache
    container_name: management_cache
    # ports:
    #   - "86:12011"
    networks:
      - db
    environment:
      CACHE_URL: http://cache:12011/cache
      LIMIT_RESPONSE_TIME: 5

  # backend:
  #   build: 
  #     context: "./Core/Backend"
  #   container_name: backend
  #   ports:
  #     - "87:12013"
  #   networks:
  #     - db
  #   environment:
  #     MANAGEMENT_FLIGHTS_API_URL: http://management_flights:12006/management-flights/flights
  #     MANAGEMENT_CUSTOMERS_API_URL: http://management_customers:12007/management-customers/customers
  #     MANAGEMENT_TICKETS_API_URL: http://management_tickets:12008/management-tickets/tickets
  #     MANAGEMENT_CACHE_API_URL: http://management_cache:12011/cache
  #     AUTHAPI_URL: http://auth:12005
  #     LIMIT_RESPONSE_TIME: 5

  # cli:
  #   build: 
  #     context: ./Client/CLI
  #   container_name: cli
  #   ports:
  #     - "90:12016"
  #   networks:
  #     - db
  #   environment:
  #     BACKEND_URL: http://backend:12013
  #     LIMIT_RESPONSE_TIME: 5
  #   stdin_open: true
  #   tty: true