version: '3.7'

networks:
  db:

services:
  psql_db:
    build:
      context: ./psql
    container_name: psql_cont
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - db