version: '3.7'

networks:
  db:

services:
  psql_db:
    build:
      context: ./psql
    container_name: psql_cont
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - db

  dal_flights:
    build: 
      context: ./Dal_flights
    container_name: dal_flights
    depends_on:
      - psql_db
    networks:
      - db
    # ports:
    #   - "87:12001"
    environment:
      PSQL_DB_USER: postgres
      PSQL_DB_PASSWORD: 123
      PSQL_DB_HOST: psql_cont
      PSQL_DB_PORT: 5432
      PSQL_DB_DBNAME: airplanesco
      PSQL_TABLE_NAME: Flights
      PSQL_LIMIT_RESPONSE_TIME: 10

  dal_customers:
    build: 
      context: ./Dal_customers
    container_name: dal_customers
    depends_on:
      - psql_db
    networks:
      - db
    # ports:
    #   - "88:12000"
    environment:
      PSQL_DB_USER: postgres
      PSQL_DB_PASSWORD: 123
      PSQL_DB_HOST: psql_cont
      PSQL_DB_PORT: 5432
      PSQL_DB_DBNAME: airplanesco
      PSQL_TABLE_NAME: Customers
      PSQL_LIMIT_RESPONSE_TIME: 10

  catalog:
    build:
      context: ./Flights_catalog
    container_name: catalog
    ports:
      - "78:12004"
    depends_on:
      - psql_db
    networks:
      - db
    environment:
      DATABASE_URL: http://dal_flights:12001/dal/flights/postgres/get #TODO: испрвить url
      DAL_LIMIT_RESPONSE_TIME: 5

  auth:
    build: 
      context: ./Auth
    container_name: auth
    ports:
      - "90:12005"
    depends_on:
      - psql_db
    networks:
      - db
    environment:
      DATABASE_URL: http://dal_customers:12000/dal/customers/postgres