version: '3.7'

networks:
  db:

services:
  psql_db:
    build:
      context: ./psql
    container_name: psql_cont
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - db

  dal_flights:
    build: 
      context: ./Dal_flights
    container_name: dal_flights
    ports:
      - "87:12001"
    depends_on:
      - psql_db
    networks:
      - db

  # dal_tickets:
  #   build: 
  #     context: ./dal_tickets
  #   container_name: dal_tickets
  #   ports:
  #     - "87:12002"
  #   depends_on:
  #     - psql_db
  #   networks:
  #     - db
